---
kind: Service
apiVersion: v1
metadata:
  name: verdict-service-k
spec:
  type: NodePort
  selector:
    app: verdict-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30501

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdict-service-deployment
  labels:
    app: verdict-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verdict-svc
  template:
    metadata:
      labels:
        app: verdict-svc
    spec:
      containers:
      - name: verdict-svc
        image: verdict-service:latest
        env:
          - name: NODE_ENV
            value: k8s
        imagePullPolicy: Never
        ports:
        - containerPort: 8080